#[cfg(windows)]
fn build_windows() {
    let file = "src/platform/windows.cc";
    let file2 = "src/platform/windows_delete_test_cert.cc";
    cc::Build::new().file(file).file(file2).compile("windows");
    println!("cargo:rustc-link-lib=WtsApi32");
    println!("cargo:rerun-if-changed={}", file);
    println!("cargo:rerun-if-changed={}", file2);
}

#[cfg(target_os = "macos")]
fn build_mac() {
    let file = "src/platform/macos.mm";
    let mut b = cc::Build::new();
    if let Ok(os_version::OsVersion::MacOS(v)) = os_version::detect() {
        let v = v.version;
        if v.contains("10.14") {
            b.flag("-DNO_InputMonitoringAuthStatus=1");
        }
    }
    b.flag("-std=c++17").file(file).compile("macos");
    println!("cargo:rerun-if-changed={}", file);
}

#[cfg(all(windows, feature = "inline"))]
fn build_manifest() {
    use std::io::Write;
    if std::env::var("PROFILE").unwrap() == "release" {
        let mut res = winres::WindowsResource::new();
        res.set_icon("res/icon.ico")
            .set_language(winapi::um::winnt::MAKELANGID(
                winapi::um::winnt::LANG_ENGLISH,
                winapi::um::winnt::SUBLANG_ENGLISH_US,
            ))
            .set_manifest_file("res/manifest.xml");
        match res.compile() {
            Err(e) => {
                write!(std::io::stderr(), "{}", e).unwrap();
                std::process::exit(1);
            }
            Ok(_) => {}
        }
    }
}

fn install_android_deps() {
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap();
    if target_os != "android" {
        return;
    }
    let mut target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    if target_arch == "x86_64" {
        target_arch = "x64".to_owned();
    } else if target_arch == "x86" {
        target_arch = "x86".to_owned();
    } else if target_arch == "aarch64" {
        target_arch = "arm64".to_owned();
    } else {
        target_arch = "arm".to_owned();
    }
    let target = format!("{}-android", target_arch);
    let vcpkg_root = std::env::var("VCPKG_ROOT").unwrap();
    let mut path: std::path::PathBuf = vcpkg_root.into();
    if let Ok(vcpkg_root) = std::env::var("VCPKG_INSTALLED_ROOT") {
        path = vcpkg_root.into();
    } else {
        path.push("installed");
    }
    path.push(target);
    println!(
        "cargo:rustc-link-search={}",
        path.join("lib").to_str().unwrap()
    );
    println!("cargo:rustc-link-lib=ndk_compat");
    println!("cargo:rustc-link-lib=oboe");
    println!("cargo:rustc-link-lib=c++");
    println!("cargo:rustc-link-lib=OpenSLES");
}

fn generate_custom_build_config() {
    use std::io::Write;
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = std::path::Path::new(&out_dir).join("custom_build_config.rs");

    let rendezvous_server = std::env::var("CUSTOM_RENDEZVOUS_SERVER").unwrap_or_default();
    let key = std::env::var("CUSTOM_KEY").unwrap_or_default();
    let api_server = std::env::var("CUSTOM_API_SERVER").unwrap_or_default();
    let relay_server = std::env::var("CUSTOM_RELAY_SERVER").unwrap_or_default();

    // Only generate meaningful content if at least one var is set, but always
    // emit the file so the `include!` always compiles.
    let content = format!(
        r#"// Auto-generated by build.rs from CUSTOM_* environment variables.
// DO NOT EDIT. Values come from the CI/CD build environment (GitHub Secrets).
pub const EMBEDDED_RENDEZVOUS_SERVER: &str = "{rendezvous_server}";
pub const EMBEDDED_KEY: &str = "{key}";
pub const EMBEDDED_API_SERVER: &str = "{api_server}";
pub const EMBEDDED_RELAY_SERVER: &str = "{relay_server}";
"#,
        rendezvous_server = rendezvous_server,
        key = key,
        api_server = api_server,
        relay_server = relay_server,
    );
    std::fs::write(&dest_path, content).unwrap();
    // Cargo rebuilds when these env vars change
    println!("cargo:rerun-if-env-changed=CUSTOM_RENDEZVOUS_SERVER");
    println!("cargo:rerun-if-env-changed=CUSTOM_KEY");
    println!("cargo:rerun-if-env-changed=CUSTOM_API_SERVER");
    println!("cargo:rerun-if-env-changed=CUSTOM_RELAY_SERVER");
}

fn main() {
    generate_custom_build_config();
    hbb_common::gen_version();
    install_android_deps();
    #[cfg(all(windows, feature = "inline"))]
    build_manifest();
    #[cfg(windows)]
    build_windows();
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap();
    if target_os == "macos" {
        #[cfg(target_os = "macos")]
        build_mac();
        println!("cargo:rustc-link-lib=framework=ApplicationServices");
    }
    println!("cargo:rerun-if-changed=build.rs");
}
