/// Module that provides compile-time embedded custom server configuration.
///
/// The actual values are generated by `build.rs` from the environment variables
/// `CUSTOM_RENDEZVOUS_SERVER`, `CUSTOM_KEY`, `CUSTOM_API_SERVER`, and
/// `CUSTOM_RELAY_SERVER` — typically sourced from GitHub Secrets in CI.
///
/// When the environment variables are absent (e.g. local development builds),
/// all accessors return empty strings and the default RustDesk server config
/// is used instead.

include!(concat!(env!("OUT_DIR"), "/custom_build_config.rs"));

/// Returns `true` if at least one custom server parameter was embedded at
/// build time, indicating this is a custom build.
#[inline]
pub fn has_embedded_custom_config() -> bool {
    !EMBEDDED_RENDEZVOUS_SERVER.is_empty() || !EMBEDDED_KEY.is_empty()
}

/// Returns the compile-time embedded rendezvous (ID) server address, e.g.
/// `"myserver.example.com"` or `"1.2.3.4"`.  Empty string means "not set".
#[inline]
pub fn get_embedded_rendezvous_server() -> &'static str {
    EMBEDDED_RENDEZVOUS_SERVER
}

/// Returns the compile-time embedded public key (base64-encoded 32-byte
/// sodiumoxide `sign::PublicKey`).  Empty string means "not set".
#[inline]
pub fn get_embedded_key() -> &'static str {
    EMBEDDED_KEY
}

/// Returns the compile-time embedded API server URL, e.g.
/// `"https://api.example.com"`.  Empty string means "not set".
#[inline]
pub fn get_embedded_api_server() -> &'static str {
    EMBEDDED_API_SERVER
}

/// Returns the compile-time embedded relay server address.  Empty string means
/// "not set", in which case the rendezvous server is used for relay as well.
#[inline]
pub fn get_embedded_relay_server() -> &'static str {
    EMBEDDED_RELAY_SERVER
}
